services:
  nginx:
    hostname: nginx
    image: nginx:1.29
    ports:
      - '80:80'
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  mediamtx:
    hostname: mediamtx
    image: bluenviron/mediamtx:1.16.3
    ports:
      - 9999:9999
    volumes:
      - ./config/mediamtx.yml:/mediamtx.yml

  database:
    hostname: database
    image: postgres:18.3
    ports:
      - 5132:5132
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=engineeredPassword
      - POSTGRES_DB=multiview
    volumes:
      - ./database/data:/var/lib/postgresql

  web:
    hostname: web
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:engineeredPassword@database:5432/multiview
      - MEDIAMTX_HOST=mediamtx
    command: sh -c "bun turbo telemetry status && bun run db:migrate && bun run build && bun run preview"
    volumes:
      - ./config/cookies.txt:/app/services/config/cookies.txt
      - ./recordings:/recordings
