module.exports = {
  apps: [
    {
      name: "internal:svelte",
      script: "bun",
      args: "x --bun vite dev --host",
      watch: false,
      env: {
        NODE_ENV: "development",
        PORT: process.env.PROD_PORT,
      },
    },
    {
      name: "internal:mediamtx",
      script: "bash",
      args: "-c ./dist/mediamtx/run.sh",
      watch: false,
    },
    {
      name: "internal:websocket-server",
      script: "./src/websocket/server.ts",
      interpreter: "bun",
      watch: true,
      ignore_watch: [
        "node_modules",
        ".pm2",
        ".svelte-kit",
        "build",
        "db",
        "config",
        "backup",
        "generated",
        "prisma",
      ],
      env: {
        NODE_ENV: "development",
      },
    },
    {
      name: "internal:instance-server",
      script: "./src/instance/server.ts",
      interpreter: "bun",
      watch: true,
      ignore_watch: [
        "node_modules",
        ".pm2",
        ".git",
        ".svelte-kit",
        "build",
        "db",
        "config",
        "backup",
        "generated",
        "prisma",
      ],
      env: {
        NODE_ENV: "development",
      },
    },
    {
      name: "internal:vod-server",
      script: "./src/vod/server.ts",
      interpreter: "bun",
      watch: true,
      ignore_watch: [
        "node_modules",
        ".pm2",
        ".git",
        ".svelte-kit",
        "build",
        "db",
        "config",
        "backup",
        "generated",
        "prisma",
      ],
      env: {
        NODE_ENV: "development",
      },
    },
    {
      name: "internal:renew-cookies",
      script: "bun",
      args: "--bun ./src/cron/renewCookies.ts",
      watch: false,
    },
    {
      name: "internal:vod-cleaner",
      script: "bun",
      args: "--bun ./src/cron/vodCleaner.ts",
      watch: false,
    },
  ],
};
