server {
    listen 80;
    server_name _;
    location / {
        proxy_pass http://web:4173;
        proxy_http_version 1.1;
        
        # # HTTP headers
        proxy_set_header Host $host;
        # proxy_set_header X-Real-IP $remote_addr;
        # proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # proxy_set_header X-Forwarded-Proto $scheme;
        
        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # SSE support
        proxy_buffering off;
        proxy_cache off;
        
        # Timeouts
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;

    }
    
    location /events/ {
        proxy_pass http://web:8080/;
        proxy_http_version 1.1;
        
        # SSE support
        proxy_buffering off;
        proxy_cache off;
        
        # Timeouts
        proxy_connect_timeout 30s;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }

    location /api/vod/ {
        proxy_pass http://web:3003/;
        proxy_http_version 1.1;
    }

    location /api/live/ {
        proxy_pass http://mediamtx:8888/;
        proxy_http_version 1.1;
        # SSE support
        proxy_buffering off;
        proxy_cache off;
    }

    location /ws {
        proxy_pass http://web:3000/;
        proxy_http_version 1.1;
        
        # WebSocket support
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # SSE support
        proxy_buffering off;
        proxy_cache off;
        
        # Timeouts
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
    }
}