import path from "path";
import puppeteer from "puppeteer";

/**
 *
 * @param {string} filePath
 * @returns {Promise<import('puppeteer').CookieData[]>}
 */
async function parseNetscapeCookies(filePath) {
  const file = Bun.file(filePath);
  const cookies = [];

  if (!file.exists()) {
    throw new Error(`${filePath} does not exist!.`);
  }

  const content = await file.text();
  const lines = content.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();

    // Skip comments and empty lines
    if (!trimmed || trimmed.startsWith("#")) continue;

    const parts = trimmed.split("\t");
    if (parts.length < 7) continue;

    // eslint-disable-next-line no-unused-vars
    const [domain, includeSubdomains, path, secure, expires, name, value] =
      parts;

    cookies.push({
      name,
      value,
      domain,
      path,
      secure: secure === "TRUE",
      expires: Number(expires) > 0 ? Number(expires) : undefined,
    });
  }

  return cookies;
}

/**
 *
 * @param {import('puppeteer').Cookie[]} cookies
 * @returns
 */
function cookiesToNetscape(cookies) {
  const timeDate = new Date();
  const lines = [
    "# Netscape HTTP Cookie File",
    `# Date updated: ${timeDate.toISOString()}`,
    "# Generated by Multiview, DO NOT EDIT!",
    "",
  ];

  for (const cookie of cookies) {
    const domain = cookie.domain.startsWith(".")
      ? cookie.domain
      : "." + cookie.domain;

    const includeSubdomains = "TRUE";
    const path = cookie.path || "/";
    const secure = cookie.secure ? "TRUE" : "FALSE";

    if (cookie.expires < 0) {
      continue;
    }
    // Netscape wants seconds, Puppeteer gives seconds already (or undefined)
    const expires = cookie.expires ? Math.floor(cookie.expires) : 0;

    lines.push(
      [
        domain,
        includeSubdomains,
        path,
        secure,
        expires,
        cookie.name,
        cookie.value,
      ].join("\t"),
    );
  }

  return lines.join("\n");
}

async function execute() {
  // Configuration: Path
  const cookiesLocation = path.resolve("config/cookies.txt");

  const cookies = await parseNetscapeCookies(cookiesLocation);
  // Launch the browser and open a new blank page.
  const browser = await puppeteer.launch({
    headless: true,
    args: ["--disable-dev-shm-usage", "--single-process", "--no-sandbox"],
  });

  await browser.setCookie(...cookies);
  const page = await browser.newPage();

  await page.goto("https://www.youtube.com/");
  await page.setViewport({ width: 1366, height: 768 });
  await page.waitForSelector("#logo-icon");
  const newCookies = await browser.cookies();

  await page.close();
  await browser.close();

  const netscapeNewCookies = cookiesToNetscape(newCookies);
  const tempFile = Bun.file(cookiesLocation);
  await tempFile.write(netscapeNewCookies);

  console.log("Renewing cookies completed. See you in another time.");

  await new Promise((resolve) =>
    setTimeout(
      () => {
        console.log("Renewed once again. ");
        resolve("Renewed");
      },
      1000 * 60 * 45,
    ),
  );
}

execute();
