import type { BunFile } from "bun";
import path from "path";
import puppeteer, {
  Browser,
  Page,
  type Cookie,
  type CookieData,
} from "puppeteer";

async function parseNetscapeCookies(filePath: string): Promise<CookieData[]> {
  const file: BunFile = Bun.file(filePath);
  const cookies: CookieData[] = [];

  if (!file.exists()) {
    throw new Error(`${filePath} does not exist!.`);
  }

  const content: string = await file.text();
  const lines: string[] = content.split("\n");

  for (const line of lines) {
    const trimmed: string = line.trim();

    // Skip comments and empty lines
    if (!trimmed || trimmed.startsWith("#")) continue;

    const parts: string[] = trimmed.split("\t");
    if (parts.length < 7) continue;

    const [
      domain,
      _includeSubdomains,
      path,
      secure,
      expires,
      name,
      value,
    ]: string[] = parts;

    cookies.push({
      name,
      value,
      domain,
      path,
      secure: secure === "TRUE",
      expires: Number(expires) > 0 ? Number(expires) : undefined,
    });
  }

  return cookies;
}

function cookiesToNetscape(cookies: Cookie[]): string {
  const timeDate: Date = new Date();
  const lines: string[] = [
    "# Netscape HTTP Cookie File",
    `# Date updated: ${timeDate.toISOString()}`,
    "# Generated by Multiview, DO NOT EDIT!",
    "",
  ];

  for (const cookie of cookies) {
    const domain = cookie.domain.startsWith(".")
      ? cookie.domain
      : "." + cookie.domain;

    const includeSubdomains: string = "TRUE";
    const path: string = cookie.path || "/";
    const secure: string = cookie.secure ? "TRUE" : "FALSE";

    if (cookie.expires < 0) {
      continue;
    }
    // Netscape wants seconds, Puppeteer gives seconds already (or undefined)
    const expires: number = cookie.expires ? Math.floor(cookie.expires) : 0;

    lines.push(
      [
        domain,
        includeSubdomains,
        path,
        secure,
        expires,
        cookie.name,
        cookie.value,
      ].join("\t"),
    );
  }

  return lines.join("\n");
}

async function execute(): Promise<void> {
  // Configuration: Path
  const cookiesLocation = path.resolve("config/cookies.txt");

  const cookies: CookieData[] = await parseNetscapeCookies(cookiesLocation);
  // Launch the browser and open a new blank page.
  const browser: Browser = await puppeteer.launch({
    headless: true,
    args: ["--disable-dev-shm-usage", "--single-process", "--no-sandbox"],
  });

  await browser.setCookie(...cookies);
  const page: Page = await browser.newPage();

  await page.goto("https://www.youtube.com/");
  await page.setViewport({ width: 1366, height: 768 });
  await page.waitForSelector("#logo-icon");
  const newCookies: Cookie[] = await browser.cookies();

  await page.close();
  await browser.close();

  const netscapeNewCookies: string = cookiesToNetscape(newCookies);
  const tempFile: BunFile = Bun.file(cookiesLocation);
  await tempFile.write(netscapeNewCookies);

  console.log("Renewing cookies completed. See you in another time.");
  await Bun.sleep(1000 * 60 * 45);
  console.log("Renewed once again. ");
}

execute();
